# Generated by Django 4.2.7 on 2023-11-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveSmallIntegerField(choices=[(1, 'FILME'), (2, 'SERIE'), (3, 'Heróis'), (4, 'Marvel'), (5, 'DC'), (6, 'HD'), (7, 'FullHd')], default=1, unique=True)),
            ],
        ),
    ]
