# Generated by Django 4.2.7 on 2024-01-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='info',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
