# Generated by Django 4.2.7 on 2023-11-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_delete_genre_alter_movie_genres'),
        ('series', '0002_season_episode'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Companies',
            new_name='Companie',
        ),
    ]
