# Generated by Django 4.2.7 on 2023-11-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('companies', '0002_rename_companies_companie'),
        ('series', '0002_season_episode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Series',
            new_name='Serie',
        ),
    ]
