# Generated by Django 4.2.7 on 2023-12-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_info'),
        ('series', '0005_alter_episode_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='info',
            field=models.ManyToManyField(to='genres.info'),
        ),
    ]
