# Generated by Django 4.2.7 on 2023-12-08 15:10

from django.db import migrations, models
import series.models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0009_alter_episode_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='playerTrailer',
            field=models.URLField(default=False),
        ),
        migrations.AlterField(
            model_name='episode',
            name='player',
            field=models.FileField(upload_to=series.models.episode_upload_path),
        ),
    ]
