# Generated by Django 4.2.7 on 2023-12-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0011_serie_age_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
