# Generated by Django 4.2.7 on 2023-12-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_info'),
        ('series', '0012_episode_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='genres',
            field=models.ManyToManyField(related_name='series', to='genres.genre'),
        ),
    ]
