# Generated by Django 4.2.7 on 2024-02-07 15:01

from django.db import migrations, models
import series.models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0017_alter_episode_playerurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='player',
            field=models.FileField(blank=True, null=True, upload_to=series.models.episode_upload_path),
        ),
    ]
