# Generated by Django 4.2.7 on 2024-02-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0018_alter_episode_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='player',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='episode',
            name='playerURL',
            field=models.URLField(blank=True, default=''),
        ),
    ]
