# Generated by Django 4.2.7 on 2024-02-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0019_alter_episode_player_alter_episode_playerurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='playerURL',
        ),
        migrations.AddField(
            model_name='episode',
            name='player_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
