# Generated by Django 4.2.7 on 2023-11-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'Ação'), (2, 'Aventura'), (3, 'Cinema de arte'), (4, 'Chanchada'), (5, 'Comédia'), (6, 'Comédia romântica'), (7, 'Dança'), (8, 'Documentário'), (9, 'Drama'), (10, 'Espionagem'), (11, 'Fantasia'), (12, 'Ficção científica'), (13, 'Guerra'), (14, 'Mistério'), (15, 'Musical'), (16, 'Policial'), (17, 'Romance'), (18, 'Terror')], default='1', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sinopse', models.TextField()),
                ('duracao', models.DurationField()),
                ('players', models.URLField()),
                ('release_date', models.DateField()),
                ('director', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companies')),
                ('genres', models.ManyToManyField(to='movies.genre')),
            ],
        ),
    ]
