# Generated by Django 4.2.7 on 2023-11-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ação'), (2, 'Aventura'), (3, 'Cinema de arte'), (4, 'Chanchada'), (5, 'Comédia'), (6, 'Comédia romântica'), (7, 'Dança'), (8, 'Documentário'), (9, 'Drama'), (10, 'Espionagem'), (11, 'Fantasia'), (12, 'Ficção científica'), (13, 'Guerra'), (14, 'Mistério'), (15, 'Musical'), (16, 'Policial'), (17, 'Romance'), (18, 'Terror')], default=1, unique=True),
        ),
    ]
