# Generated by Django 4.2.7 on 2023-11-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_genre_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='duracao',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='players',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='sinopse',
            new_name='synopsis',
        ),
    ]
