# Generated by Django 4.2.7 on 2023-11-21 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_movie_slug_movie_hash_id_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='hash_id_player',
        ),
    ]
