# Generated by Django 4.2.7 on 2023-11-22 14:44

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_rename_hash_player_movie_hash_id_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age_groups',
            field=models.IntegerField(choices=[(1, 'LIVRE'), (2, '+10'), (3, '+16'), (4, '+18')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='coverOne',
            field=models.FileField(upload_to=movies.models.movie_upload_path),
        ),
        migrations.AlterField(
            model_name='movie',
            name='coverTwo',
            field=models.FileField(upload_to=movies.models.movie_upload_path),
        ),
        migrations.AlterField(
            model_name='movie',
            name='highlight',
            field=models.FileField(upload_to=movies.models.movie_upload_path),
        ),
    ]
