# Generated by Django 4.2.7 on 2023-11-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_movie_age_groups_alter_movie_coverone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_groups',
            field=models.IntegerField(choices=[(1, 'LIVRE'), (2, '+10'), (3, '+16'), (4, '+18')], default=1),
        ),
    ]
