# Generated by Django 4.2.7 on 2023-11-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_info'),
        ('movies', '0014_alter_movie_age_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='info',
            field=models.ManyToManyField(to='genres.info'),
        ),
    ]
