# Generated by Django 4.2.7 on 2023-11-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_movie_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='hash_id_player',
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_groups',
            field=models.IntegerField(choices=[(1, 'LIVRE'), (2, '+10'), (3, '+12'), (4, '+16'), (5, '+18')], default=1),
        ),
    ]
