# Generated by Django 4.2.7 on 2023-11-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_remove_movie_coverone_remove_movie_covertwo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='player',
            field=models.CharField(default='https://google.com', max_length=100),
        ),
    ]
