# Generated by Django 4.2.7 on 2023-11-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_movie_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='player',
            field=models.URLField(default='https://google.com', max_length=100),
        ),
    ]
