# Generated by Django 4.2.7 on 2023-11-24 19:55

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_alter_movie_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='coverOne',
            field=models.FileField(default=1, upload_to=movies.models.movie_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='coverTwo',
            field=models.FileField(default=1, upload_to=movies.models.movie_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='highlight',
            field=models.FileField(default=1, upload_to=movies.models.movie_upload_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='player',
            field=models.FileField(upload_to=movies.models.movie_upload_path),
        ),
    ]
