# Generated by Django 4.2.7 on 2023-12-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_movie_coverone_movie_covertwo_movie_highlight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
