# Generated by Django 4.2.7 on 2023-12-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_movie_file_size_alter_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
