# Generated by Django 4.2.7 on 2024-01-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
