# Generated by Django 4.2.7 on 2024-02-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0027_alter_movie_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='playerURL',
            field=models.URLField(blank=True),
        ),
    ]
