# Generated by Django 4.2.7 on 2024-02-07 15:01

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0028_alter_movie_playerurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='player',
            field=models.FileField(blank=True, null=True, upload_to=movies.models.movie_upload_path),
        ),
    ]
