# Generated by Django 4.2.7 on 2024-02-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0029_alter_movie_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='playerURL',
            field=models.URLField(blank=True, default=''),
        ),
    ]
