# Generated by Django 4.2.7 on 2024-02-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0032_rename_playerurl_movie_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='player_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
