# Generated by Django 4.2.7 on 2024-02-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0033_alter_movie_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
